complete -c gsc -n "__fish_use_subcommand" -s v -l verbose -d 'Makes the output more verbose'
complete -c gsc -n "__fish_use_subcommand" -s q -l quiet -d 'Makes the output quieter'
complete -c gsc -n "__fish_use_subcommand" -s j -l json -d 'Show raw JSON response'
complete -c gsc -n "__fish_use_subcommand" -s H -l human -d 'Show human-formatted result (overrides --json)'
complete -c gsc -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c gsc -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c gsc -n "__fish_use_subcommand" -f -a "auth" -d 'Authenticates with the server'
complete -c gsc -n "__fish_use_subcommand" -f -a "cat" -d 'Prints remote files to stdout'
complete -c gsc -n "__fish_use_subcommand" -f -a "cp" -d 'Copies files to or from the server'
complete -c gsc -n "__fish_use_subcommand" -f -a "deauth" -d 'Forgets authentication credentials'
complete -c gsc -n "__fish_use_subcommand" -f -a "eval" -d 'Manages self evaluation'
complete -c gsc -n "__fish_use_subcommand" -f -a "ls" -d 'Lists files'
complete -c gsc -n "__fish_use_subcommand" -f -a "mv" -d 'Renames a remote file'
complete -c gsc -n "__fish_use_subcommand" -f -a "partner" -d 'Manages partners'
complete -c gsc -n "__fish_use_subcommand" -f -a "rm" -d 'Removes remote files'
complete -c gsc -n "__fish_use_subcommand" -f -a "status" -d 'Retrieves user or submission status'
complete -c gsc -n "__fish_use_subcommand" -f -a "whoami" -d 'Prints your username, if authenticated'
complete -c gsc -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c gsc -n "__fish_seen_subcommand_from auth" -s v -l verbose -d 'Makes the output more verbose'
complete -c gsc -n "__fish_seen_subcommand_from auth" -s q -l quiet -d 'Makes the output quieter'
complete -c gsc -n "__fish_seen_subcommand_from auth" -s j -l json -d 'Show raw JSON response'
complete -c gsc -n "__fish_seen_subcommand_from auth" -s H -l human -d 'Show human-formatted result (overrides --json)'
complete -c gsc -n "__fish_seen_subcommand_from auth" -s h -l help -d 'Prints help information'
complete -c gsc -n "__fish_seen_subcommand_from auth" -s V -l version -d 'Prints version information'
complete -c gsc -n "__fish_seen_subcommand_from cat" -s v -l verbose -d 'Makes the output more verbose'
complete -c gsc -n "__fish_seen_subcommand_from cat" -s q -l quiet -d 'Makes the output quieter'
complete -c gsc -n "__fish_seen_subcommand_from cat" -s j -l json -d 'Show raw JSON response'
complete -c gsc -n "__fish_seen_subcommand_from cat" -s H -l human -d 'Show human-formatted result (overrides --json)'
complete -c gsc -n "__fish_seen_subcommand_from cat" -s a -l all -d 'Print all files in the specified homeworks'
complete -c gsc -n "__fish_seen_subcommand_from cat" -s h -l help -d 'Prints help information'
complete -c gsc -n "__fish_seen_subcommand_from cat" -s V -l version -d 'Prints version information'
complete -c gsc -n "__fish_seen_subcommand_from cp" -s v -l verbose -d 'Makes the output more verbose'
complete -c gsc -n "__fish_seen_subcommand_from cp" -s q -l quiet -d 'Makes the output quieter'
complete -c gsc -n "__fish_seen_subcommand_from cp" -s j -l json -d 'Show raw JSON response'
complete -c gsc -n "__fish_seen_subcommand_from cp" -s H -l human -d 'Show human-formatted result (overrides --json)'
complete -c gsc -n "__fish_seen_subcommand_from cp" -s f -d 'Overwrite existing files without asking'
complete -c gsc -n "__fish_seen_subcommand_from cp" -s i -d 'Ask (interactively) before overwriting existing files'
complete -c gsc -n "__fish_seen_subcommand_from cp" -s n -d 'Never overwrite existing files'
complete -c gsc -n "__fish_seen_subcommand_from cp" -s a -l all -d 'Copy all the files in the specified source homeworks'
complete -c gsc -n "__fish_seen_subcommand_from cp" -s h -l help -d 'Prints help information'
complete -c gsc -n "__fish_seen_subcommand_from cp" -s V -l version -d 'Prints version information'
complete -c gsc -n "__fish_seen_subcommand_from deauth" -s v -l verbose -d 'Makes the output more verbose'
complete -c gsc -n "__fish_seen_subcommand_from deauth" -s q -l quiet -d 'Makes the output quieter'
complete -c gsc -n "__fish_seen_subcommand_from deauth" -s j -l json -d 'Show raw JSON response'
complete -c gsc -n "__fish_seen_subcommand_from deauth" -s H -l human -d 'Show human-formatted result (overrides --json)'
complete -c gsc -n "__fish_seen_subcommand_from deauth" -s h -l help -d 'Prints help information'
complete -c gsc -n "__fish_seen_subcommand_from deauth" -s V -l version -d 'Prints version information'
complete -c gsc -n "__fish_seen_subcommand_from eval" -s v -l verbose -d 'Makes the output more verbose'
complete -c gsc -n "__fish_seen_subcommand_from eval" -s q -l quiet -d 'Makes the output quieter'
complete -c gsc -n "__fish_seen_subcommand_from eval" -s j -l json -d 'Show raw JSON response'
complete -c gsc -n "__fish_seen_subcommand_from eval" -s H -l human -d 'Show human-formatted result (overrides --json)'
complete -c gsc -n "__fish_seen_subcommand_from eval" -s h -l help -d 'Prints help information'
complete -c gsc -n "__fish_seen_subcommand_from eval" -s V -l version -d 'Prints version information'
complete -c gsc -n "__fish_seen_subcommand_from eval" -f -a "get" -d 'Shows evaluation'
complete -c gsc -n "__fish_seen_subcommand_from eval" -f -a "set" -d 'Performs self evaluation'
complete -c gsc -n "__fish_seen_subcommand_from eval" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c gsc -n "__fish_seen_subcommand_from get" -s h -l help -d 'Prints help information'
complete -c gsc -n "__fish_seen_subcommand_from get" -s V -l version -d 'Prints version information'
complete -c gsc -n "__fish_seen_subcommand_from set" -s h -l help -d 'Prints help information'
complete -c gsc -n "__fish_seen_subcommand_from set" -s V -l version -d 'Prints version information'
complete -c gsc -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c gsc -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c gsc -n "__fish_seen_subcommand_from ls" -s v -l verbose -d 'Makes the output more verbose'
complete -c gsc -n "__fish_seen_subcommand_from ls" -s q -l quiet -d 'Makes the output quieter'
complete -c gsc -n "__fish_seen_subcommand_from ls" -s j -l json -d 'Show raw JSON response'
complete -c gsc -n "__fish_seen_subcommand_from ls" -s H -l human -d 'Show human-formatted result (overrides --json)'
complete -c gsc -n "__fish_seen_subcommand_from ls" -s h -l help -d 'Prints help information'
complete -c gsc -n "__fish_seen_subcommand_from ls" -s V -l version -d 'Prints version information'
complete -c gsc -n "__fish_seen_subcommand_from mv" -s v -l verbose -d 'Makes the output more verbose'
complete -c gsc -n "__fish_seen_subcommand_from mv" -s q -l quiet -d 'Makes the output quieter'
complete -c gsc -n "__fish_seen_subcommand_from mv" -s j -l json -d 'Show raw JSON response'
complete -c gsc -n "__fish_seen_subcommand_from mv" -s H -l human -d 'Show human-formatted result (overrides --json)'
complete -c gsc -n "__fish_seen_subcommand_from mv" -s f -d 'Overwrite existing files without asking'
complete -c gsc -n "__fish_seen_subcommand_from mv" -s i -d 'Ask (interactively) before overwriting existing files'
complete -c gsc -n "__fish_seen_subcommand_from mv" -s n -d 'Never overwrite existing files'
complete -c gsc -n "__fish_seen_subcommand_from mv" -s h -l help -d 'Prints help information'
complete -c gsc -n "__fish_seen_subcommand_from mv" -s V -l version -d 'Prints version information'
complete -c gsc -n "__fish_seen_subcommand_from partner" -s v -l verbose -d 'Makes the output more verbose'
complete -c gsc -n "__fish_seen_subcommand_from partner" -s q -l quiet -d 'Makes the output quieter'
complete -c gsc -n "__fish_seen_subcommand_from partner" -s j -l json -d 'Show raw JSON response'
complete -c gsc -n "__fish_seen_subcommand_from partner" -s H -l human -d 'Show human-formatted result (overrides --json)'
complete -c gsc -n "__fish_seen_subcommand_from partner" -s h -l help -d 'Prints help information'
complete -c gsc -n "__fish_seen_subcommand_from partner" -s V -l version -d 'Prints version information'
complete -c gsc -n "__fish_seen_subcommand_from partner" -f -a "request" -d 'Sends a partner request'
complete -c gsc -n "__fish_seen_subcommand_from partner" -f -a "accept" -d 'Accepts a partner request'
complete -c gsc -n "__fish_seen_subcommand_from partner" -f -a "cancel" -d 'Cancels a partner request'
complete -c gsc -n "__fish_seen_subcommand_from partner" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c gsc -n "__fish_seen_subcommand_from request" -s v -l verbose -d 'Makes the output more verbose'
complete -c gsc -n "__fish_seen_subcommand_from request" -s q -l quiet -d 'Makes the output quieter'
complete -c gsc -n "__fish_seen_subcommand_from request" -s j -l json -d 'Show raw JSON response'
complete -c gsc -n "__fish_seen_subcommand_from request" -s H -l human -d 'Show human-formatted result (overrides --json)'
complete -c gsc -n "__fish_seen_subcommand_from request" -s h -l help -d 'Prints help information'
complete -c gsc -n "__fish_seen_subcommand_from request" -s V -l version -d 'Prints version information'
complete -c gsc -n "__fish_seen_subcommand_from accept" -s v -l verbose -d 'Makes the output more verbose'
complete -c gsc -n "__fish_seen_subcommand_from accept" -s q -l quiet -d 'Makes the output quieter'
complete -c gsc -n "__fish_seen_subcommand_from accept" -s j -l json -d 'Show raw JSON response'
complete -c gsc -n "__fish_seen_subcommand_from accept" -s H -l human -d 'Show human-formatted result (overrides --json)'
complete -c gsc -n "__fish_seen_subcommand_from accept" -s h -l help -d 'Prints help information'
complete -c gsc -n "__fish_seen_subcommand_from accept" -s V -l version -d 'Prints version information'
complete -c gsc -n "__fish_seen_subcommand_from cancel" -s v -l verbose -d 'Makes the output more verbose'
complete -c gsc -n "__fish_seen_subcommand_from cancel" -s q -l quiet -d 'Makes the output quieter'
complete -c gsc -n "__fish_seen_subcommand_from cancel" -s j -l json -d 'Show raw JSON response'
complete -c gsc -n "__fish_seen_subcommand_from cancel" -s H -l human -d 'Show human-formatted result (overrides --json)'
complete -c gsc -n "__fish_seen_subcommand_from cancel" -s h -l help -d 'Prints help information'
complete -c gsc -n "__fish_seen_subcommand_from cancel" -s V -l version -d 'Prints version information'
complete -c gsc -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c gsc -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
complete -c gsc -n "__fish_seen_subcommand_from rm" -s v -l verbose -d 'Makes the output more verbose'
complete -c gsc -n "__fish_seen_subcommand_from rm" -s q -l quiet -d 'Makes the output quieter'
complete -c gsc -n "__fish_seen_subcommand_from rm" -s j -l json -d 'Show raw JSON response'
complete -c gsc -n "__fish_seen_subcommand_from rm" -s H -l human -d 'Show human-formatted result (overrides --json)'
complete -c gsc -n "__fish_seen_subcommand_from rm" -s a -l all -d 'Remove all the files in the specified homework'
complete -c gsc -n "__fish_seen_subcommand_from rm" -s h -l help -d 'Prints help information'
complete -c gsc -n "__fish_seen_subcommand_from rm" -s V -l version -d 'Prints version information'
complete -c gsc -n "__fish_seen_subcommand_from status" -s v -l verbose -d 'Makes the output more verbose'
complete -c gsc -n "__fish_seen_subcommand_from status" -s q -l quiet -d 'Makes the output quieter'
complete -c gsc -n "__fish_seen_subcommand_from status" -s j -l json -d 'Show raw JSON response'
complete -c gsc -n "__fish_seen_subcommand_from status" -s H -l human -d 'Show human-formatted result (overrides --json)'
complete -c gsc -n "__fish_seen_subcommand_from status" -s h -l help -d 'Prints help information'
complete -c gsc -n "__fish_seen_subcommand_from status" -s V -l version -d 'Prints version information'
complete -c gsc -n "__fish_seen_subcommand_from whoami" -s v -l verbose -d 'Makes the output more verbose'
complete -c gsc -n "__fish_seen_subcommand_from whoami" -s q -l quiet -d 'Makes the output quieter'
complete -c gsc -n "__fish_seen_subcommand_from whoami" -s j -l json -d 'Show raw JSON response'
complete -c gsc -n "__fish_seen_subcommand_from whoami" -s H -l human -d 'Show human-formatted result (overrides --json)'
complete -c gsc -n "__fish_seen_subcommand_from whoami" -s h -l help -d 'Prints help information'
complete -c gsc -n "__fish_seen_subcommand_from whoami" -s V -l version -d 'Prints version information'
complete -c gsc -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c gsc -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
