#!/bin/sh

set -e

srcdir=/home/jesse/pub/etc/
dstdir=${HOME%/}/
prog=${0##*/}

if [ -n "$1" ]; then
    dstdir=${1%/}/
fi

backup_file () {
    local dst=$1
    test -f "$dst" || return 0

    local bak
    local descr
    case "$dst" in
        *.pre211\~*)
            bak=$dst\~
            descr='older'
            ;;
        *.pre211)
            bak=$dst\~
            descr='previous'
            ;;
        *)
            bak=$dst.pre211
            descr='your existing'
            ;;
    esac

    backup_file "$bak"
    mv "$dst" "$bak"
    echo " • Saved $descr ${dst##*/} as ${bak##*/}"
}

replace_file () {
    local src=${srcdir}$1
    local dst=${dstdir}.$1

    if ! [ -f "$src" ]; then
        exec >&2
        echo "$prog: error: Could not install ${dst##*/}"
        echo "This is quite surprising. Please report a bug."
        exit 1
    fi

    if diff "$src" "$dst" >/dev/null 2>&1; then
        echo >&2 "$prog: warning: You already have my ${dst##*/}; skipping..."
        return 0
    fi

    backup_file "$dst"
    cp "$src" "$dst"
    echo " • Installed ${dst##*/} to $dstdir"
}

echo "Installing CS 211’s default dotfiles to $dstdir..."
replace_file tcshrc
replace_file emacs
echo "Installation complete."
