#!/bin/sh

# Checks source files for style.

use_clang=

case "$1" in
    -c)
        use_clang=1
        shift
        ;;
    -k)
        shift
        ;;
    *)
        ;;
esac

if [ -z "$1" ]; then
    echo >&2 "Usage: $(basename $0) [-c|-k] FILES ..."
    exit 1
fi

if [ -n "$use_clang" ]; then
    $TOV_PUB/bin/install-clang-format211
    $TOV_PUB/bin/run-clang-format.py "$@"
else
    xml=$TOV_PUB/etc/KWStyle.xml

    for file; do
        $TOV_PUB/bin/KWStyle -v -xml "$xml" "$file"
    done
fi
