#!/bin/sh

# Creats a .clang-format in the user's home directory if there
# isn't one there already.

USER_CONFIG="$HOME/.clang-format"
COURSE_CONFIG="$TOV_PUB/etc/clang-format211"

if ! [ -e "$USER_CONFIG" ]; then
    ln -s "$COURSE_CONFIG" "$USER_CONFIG"
fi

